name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  #release:
  #  types: [published]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1.Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: 1/3 Checks-out SDKs.DjiImage
      - uses: actions/checkout@v3
      # 2.build
      - name: 2.1/3 Install dependencies
        run: dotnet restore SDKs.DjiImage
      - name: 2.2/3 Build SDKs.DjiImage
        run: dotnet build --configuration Release SDKs.DjiImage
      - name: 2.3/3 Create package
        run: dotnet pack --configuration Release SDKs.DjiImage
      # 3.Authenticates packages to push to nuget.org.
      - name: 3/3 Publish the package to nuget.org
      - uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
        run: dotnet nuget push */bin/Release/*.nupkg -k $NUGET_AUTH_TOKEN -s https://api.nuget.org/v3/index.json
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.NUGET_TOKEN }}
