name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: 1.Setup .NET Standard SDK
      - uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
          source-url: https://nuget.pkg.github.com/willzou/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: 2.Install Dependencies
        run: dotnet restore 
      - name: 3.Build
        run: dotnet build -c Release SDKs.DjiImage/SDKs.DjiImage.csproj
      - name: 4.Create Nuget Package
        run: dotnet pack --no-build -c Release SDKs.DjiImage/SDKs.DjiImage.csproj
      - name: 5.Publish the package to nuget.org
        run: dotnet nuget push SDKs.DjiImage/bin/Release/*.nupkg -k $NUGET_AUTH_TOKEN -s https://api.nuget.org/v3/index.json -NoSymbol
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.NUGET_TOKEN }}