name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  #release:
  #  types: [published]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: 1.Setup .NET Standard SDK
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
      - name: 2.Build SDKs.DjiImage
        run: dotnet build SDKs.DjiImage/SDKs.DjiImage.csproj --configuration Release
      - name: 3.Create nuget package
        run: dotnet pack SDKs.DjiImage/SDKs.DjiImage.csproj --configuration Release --no-build
      - name: 4.Publish the package to nuget.org
        run: |
            dotnet nuget push SDKs.DjiImage/bin/Release/*.nupkg --api-key ${{secrets.NUGET_TOKEN}} --source https://api.nuget.org/v3/index.json --skip-duplicate